name: CI

on:
  push:
    branches: ["*"] # Trigger on push to any branch
  pull_request:
    branches: ["*"] # Trigger on PR to any branch
  workflow_dispatch: # Allow manual runs

  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 --max-line-length=90 --ignore=E302,E305 app.py

      - name: Run unit tests
        run: |
          echo "def add(a,b): return a+b" > test_sample.py
          echo "def test_add(): assert add(2,3) == 5" >> test_sample.py
          pip install pytest
          pytest test_sample.py

      - name: Build Docker image
        run: docker build -t flask-app:latest .
